"""Explicit tool registry and workspace-aware tool implementations."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Callable

from . import mpnet as mpnet_utils
from share.workspace.store import ArtifactRef, RunRecord, SessionEvent, WorkspaceStore, dump_json, load_json, utc_now


ConfirmationLevel = str
ToolHandler = Callable[..., "ToolResult"]


@dataclass(slots=True)
class ToolSpec:
    """Inspectable tool metadata exposed to the runtime and CLI."""

    name: str
    description: str
    input_schema: dict[str, Any] = field(default_factory=dict)
    confirmation: ConfirmationLevel | None = None


@dataclass(slots=True)
class ToolCall:
    """Structured tool invocation generated by the agent or CLI."""

    name: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ToolResult:
    """Result payload returned by one tool invocation."""

    name: str
    ok: bool
    content: str
    data: dict[str, Any] = field(default_factory=dict)
    error: str | None = None

    def to_message(self) -> str:
        status = "ok" if self.ok else "error"
        payload = {
            "status": status,
            "content": self.content,
            "data": self.data,
        }
        if self.error is not None:
            payload["error"] = self.error
        return json.dumps(payload, indent=2, sort_keys=True)


class ToolRegistry:
    """Simple in-memory registry of explicit workspace tools."""

    def __init__(self) -> None:
        self._specs: dict[str, ToolSpec] = {}
        self._handlers: dict[str, ToolHandler] = {}

    def register(self, spec: ToolSpec, handler: ToolHandler) -> None:
        self._specs[spec.name] = spec
        self._handlers[spec.name] = handler

    def specs(self) -> list[ToolSpec]:
        return [self._specs[name] for name in sorted(self._specs)]

    def get_spec(self, name: str) -> ToolSpec:
        return self._specs[name]

    def execute(self, tool_call: ToolCall) -> ToolResult:
        handler = self._handlers.get(tool_call.name)
        if handler is None:
            return ToolResult(name=tool_call.name, ok=False, content="", error=f"Unknown tool '{tool_call.name}'")
        try:
            return handler(**tool_call.arguments)
        except Exception as exc:  # noqa: BLE001
            return ToolResult(name=tool_call.name, ok=False, content="", error=str(exc))


class WorkspaceAppRunner:
    """Launch share/LeRobot scripts and persist their run metadata."""

    def __init__(self, store: WorkspaceStore, repo_root: Path | None = None):
        self.store = store
        self.repo_root = (repo_root or Path(__file__).resolve().parents[3]).resolve()

    def run_subprocess(
        self,
        *,
        project: str,
        task: str,
        run_type: str,
        command: list[str],
        prepared_run: RunRecord | None = None,
        mp_net: str | None = None,
        mp_net_version: str | None = None,
        primitive: str | None = None,
        policy_id: str | None = None,
        dataset_id: str | None = None,
        cwd: str | None = None,
        notes: str | None = None,
    ) -> RunRecord:
        """Run one subprocess, capture logs, and persist its run record."""
        record = prepared_run or self.store.create_run(
            project,
            task,
            run_type=run_type,
            status="running",
            command=command,
            cwd=cwd or str(self.repo_root),
            mp_net=mp_net,
            mp_net_version=mp_net_version,
            primitive=primitive,
            policy_id=policy_id,
            dataset_id=dataset_id,
            notes=notes,
        )
        record.run_type = run_type
        record.status = "running"
        record.command = command
        record.cwd = cwd or str(self.repo_root)
        record.mp_net = mp_net or record.mp_net
        record.mp_net_version = mp_net_version or record.mp_net_version
        record.primitive = primitive or record.primitive
        record.policy_id = policy_id or record.policy_id
        record.dataset_id = dataset_id or record.dataset_id
        record.notes = notes or record.notes
        self.store.save_run(project, task, record)
        run_dir = self.store.run_dir(project, task, record.run_id)
        completed = subprocess.run(
            command,
            cwd=cwd or self.repo_root,
            text=True,
            capture_output=True,
            check=False,
        )
        Path(record.stdout_path).write_text(completed.stdout, encoding="utf-8")
        Path(record.stderr_path).write_text(completed.stderr, encoding="utf-8")
        record.status = "succeeded" if completed.returncode == 0 else "failed"
        record.ended_at = utc_now()
        record.updated_at = record.ended_at
        summary_path = Path(record.summary_path) if record.summary_path is not None else run_dir / "summary.json"
        summary_payload = load_json(summary_path, default=None)
        if summary_payload is None:
            summary_payload = {
                "returncode": completed.returncode,
                "command": command,
                "stdout_path": record.stdout_path,
                "stderr_path": record.stderr_path,
            }
            dump_json(summary_path, summary_payload)
        record.summary_path = str(summary_path)
        if isinstance(summary_payload, dict):
            record.metrics = summary_payload.get("metrics", summary_payload)
            if "output_paths" in summary_payload and isinstance(summary_payload["output_paths"], list):
                record.output_paths = [str(item) for item in summary_payload["output_paths"]]
        self.store.save_run(project, task, record)
        return record


class WorkspaceToolbox:
    """Collection of first-class workspace tools bound to one project/task."""

    def __init__(
        self,
        store: WorkspaceStore,
        project: str,
        task: str,
        *,
        repo_root: Path | None = None,
    ):
        self.store = store
        self.project = project
        self.task = task
        self.repo_root = (repo_root or Path(__file__).resolve().parents[3]).resolve()
        self.registry = ToolRegistry()
        self.runner = WorkspaceAppRunner(store=store, repo_root=self.repo_root)
        self._register_tools()

    def _register_tools(self) -> None:
        self.registry.register(
            ToolSpec("status", "Summarize the current workspace, task, active MP-Net, and latest runs."),
            self.status,
        )
        self.registry.register(
            ToolSpec("list_mp_nets", "List MP-Nets known to the current task."),
            self.list_mp_nets,
        )
        self.registry.register(
            ToolSpec(
                "summarize_current_mpnet",
                "Summarize the active MP-Net graph and primitive structure.",
                {"name": {"type": "string", "optional": True}},
            ),
            self.summarize_current_mpnet,
        )
        self.registry.register(
            ToolSpec(
                "list_primitives",
                "List primitives in the selected MP-Net.",
                {"name": {"type": "string", "optional": True}},
            ),
            self.list_primitives,
        )
        self.registry.register(
            ToolSpec(
                "describe_transitions",
                "Describe transitions in the selected MP-Net.",
                {"name": {"type": "string", "optional": True}},
            ),
            self.describe_transitions,
        )
        self.registry.register(
            ToolSpec("read_notes", "Read task notes from the workspace."),
            self.read_notes,
        )
        self.registry.register(
            ToolSpec(
                "save_notes",
                "Replace task notes in the workspace.",
                {"notes": {"type": "string"}},
                confirmation="config_write",
            ),
            self.save_notes,
        )
        self.registry.register(
            ToolSpec(
                "create_mpnet",
                "Create a new MP-Net from a minimal terminal template.",
                {
                    "name": {"type": "string"},
                    "primitive_name": {"type": "string", "optional": True},
                    "notes": {"type": "string", "optional": True},
                    "description": {"type": "string", "optional": True},
                },
                confirmation="config_write",
            ),
            self.create_mpnet,
        )
        self.registry.register(
            ToolSpec(
                "import_mpnet",
                "Import an MP-Net JSON file into the workspace and version it.",
                {"name": {"type": "string"}, "path": {"type": "string"}},
                confirmation="config_write",
            ),
            self.import_mpnet,
        )
        self.registry.register(
            ToolSpec(
                "edit_mpnet",
                "Apply a structured MP-Net edit operation and write a new version.",
                {
                    "name": {"type": "string", "optional": True},
                    "operation": {"type": "string"},
                    "arguments": {"type": "object"},
                    "description": {"type": "string", "optional": True},
                },
                confirmation="config_write",
            ),
            self.edit_mpnet,
        )
        self.registry.register(
            ToolSpec(
                "validate_mpnet",
                "Validate an MP-Net without moving hardware.",
                {"name": {"type": "string", "optional": True}},
            ),
            self.validate_mpnet,
        )
        self.registry.register(
            ToolSpec("list_runs", "List recent runs for the current task."),
            self.list_runs,
        )
        self.registry.register(
            ToolSpec("summarize_latest_evals", "Summarize the latest evaluation-style runs."),
            self.summarize_latest_evals,
        )
        self.registry.register(
            ToolSpec(
                "compare_runs",
                "Compare two stored runs.",
                {"run_a": {"type": "string"}, "run_b": {"type": "string"}},
            ),
            self.compare_runs,
        )
        self.registry.register(
            ToolSpec(
                "pin_artifact",
                "Store a dataset, policy, or report reference in the workspace.",
                {
                    "kind": {"type": "string"},
                    "path": {"type": "string"},
                    "label": {"type": "string", "optional": True},
                    "metadata": {"type": "object", "optional": True},
                    "mp_net": {"type": "string", "optional": True},
                },
                confirmation="config_write",
            ),
            self.pin_artifact,
        )
        self.registry.register(
            ToolSpec(
                "run_demo_mpnet",
                "Launch the existing demo_mp_net example as a no-hardware smoke test.",
                {},
            ),
            self.run_demo_mpnet,
        )
        self.registry.register(
            ToolSpec(
                "run_recording",
                "Launch demonstration recording for the selected MP-Net.",
                {
                    "name": {"type": "string", "optional": True},
                    "dataset_repo_id": {"type": "string"},
                    "dataset_root": {"type": "string"},
                    "single_task": {"type": "string"},
                    "num_episodes": {"type": "integer", "optional": True},
                    "episode_time_s": {"type": "integer", "optional": True},
                    "interactive": {"type": "boolean", "optional": True},
                },
                confirmation="hardware_motion",
            ),
            self.run_recording,
        )
        self.registry.register(
            ToolSpec(
                "run_training",
                "Launch the thin share-level training adapter.",
                {
                    "policy_path": {"type": "string"},
                    "dataset_repo_id": {"type": "string"},
                    "dataset_root": {"type": "string"},
                    "output_dir": {"type": "string"},
                    "steps": {"type": "integer", "optional": True},
                    "batch_size": {"type": "integer", "optional": True},
                    "eval_freq": {"type": "integer", "optional": True},
                    "job_name": {"type": "string", "optional": True},
                },
                confirmation="expensive_run",
            ),
            self.run_training,
        )
        self.registry.register(
            ToolSpec(
                "run_evaluation",
                "Launch the lightweight dataset evaluation adapter.",
                {
                    "policy_path": {"type": "string"},
                    "dataset_root": {"type": "string"},
                    "output_dir": {"type": "string"},
                    "metrics_file": {"type": "string", "optional": True},
                },
                confirmation="expensive_run",
            ),
            self.run_evaluation,
        )
        self.registry.register(
            ToolSpec(
                "register_run",
                "Register an externally completed run in the workspace.",
                {
                    "run_type": {"type": "string"},
                    "status": {"type": "string"},
                    "notes": {"type": "string", "optional": True},
                    "metrics": {"type": "object", "optional": True},
                    "command": {"type": "array", "optional": True},
                },
                confirmation="config_write",
            ),
            self.register_run,
        )

    def tool_specs_payload(self) -> list[dict[str, Any]]:
        return [asdict(spec) for spec in self.registry.specs()]

    def _load_selected_mpnet(self, name: str | None = None) -> tuple[str, str | None, Any]:
        task_record = self.store.ensure_task(self.project, self.task)
        selected_name = name or task_record.active_mp_net
        if selected_name is None:
            raise ValueError("No active MP-Net is set for the current task")
        path = self.store.mp_net_current_path(self.project, self.task, selected_name)
        if not path.exists():
            raise FileNotFoundError(f"MP-Net '{selected_name}' has no current.json in the workspace")
        config = mpnet_utils.load_mpnet_config(path)
        version = task_record.mp_nets[selected_name].current_version if selected_name in task_record.mp_nets else None
        return selected_name, version, config

    def _save_selected_mpnet(
        self,
        name: str,
        config: Any,
        *,
        description: str | None = None,
        origin_path: str | None = None,
        set_active: bool = True,
    ) -> dict[str, Any]:
        task_record = self.store.ensure_task(self.project, self.task)
        previous_version = task_record.mp_nets.get(name).current_version if name in task_record.mp_nets else None
        version_index = 1
        if previous_version and previous_version.startswith("v"):
            try:
                version_index = int(previous_version[1:]) + 1
            except ValueError:
                version_index = 1
        version_id = f"v{version_index:04d}"
        config = mpnet_utils.validate_mpnet_config(config)
        version_path = self.store.mp_net_version_path(self.project, self.task, name, version_id)
        current_path = self.store.mp_net_current_path(self.project, self.task, name)
        mpnet_utils.save_mpnet_config(config, version_path)
        shutil.copyfile(version_path, current_path)
        self.store.register_mp_net(
            self.project,
            self.task,
            name,
            version_id=version_id,
            origin_path=origin_path,
            description=description,
            set_active=set_active,
        )
        return {"name": name, "version_id": version_id, "path": str(current_path)}

    def status(self) -> ToolResult:
        workspace = self.store.ensure_workspace(project=self.project, task=self.task)
        task_record = self.store.ensure_task(self.project, self.task)
        runs = self.store.list_runs(self.project, self.task)[:5]
        artifacts = self.store.load_artifacts(self.project, self.task)[:5]
        payload = {
            "workspace": workspace.name,
            "project": self.project,
            "task": self.task,
            "active_mp_net": task_record.active_mp_net,
            "mp_nets": [asdict(item) for item in self.store.list_mp_nets(self.project, self.task)],
            "latest_run_id": task_record.latest_run_id,
            "recent_runs": [asdict(run) for run in runs],
            "recent_artifacts": [asdict(artifact) for artifact in artifacts],
        }
        return ToolResult(name="status", ok=True, content="Current task status", data=payload)

    def list_mp_nets(self) -> ToolResult:
        items = [asdict(item) for item in self.store.list_mp_nets(self.project, self.task)]
        return ToolResult(name="list_mp_nets", ok=True, content=f"Found {len(items)} MP-Nets", data={"mp_nets": items})

    def summarize_current_mpnet(self, name: str | None = None) -> ToolResult:
        selected_name, version, config = self._load_selected_mpnet(name)
        summary = mpnet_utils.summarize_mpnet(config)
        summary["name"] = selected_name
        summary["version"] = version
        return ToolResult(name="summarize_current_mpnet", ok=True, content=f"Summary for MP-Net '{selected_name}'", data=summary)

    def list_primitives(self, name: str | None = None) -> ToolResult:
        selected_name, _, config = self._load_selected_mpnet(name)
        return ToolResult(
            name="list_primitives",
            ok=True,
            content=f"Primitive list for '{selected_name}'",
            data={"name": selected_name, "primitives": mpnet_utils.list_primitives(config)},
        )

    def describe_transitions(self, name: str | None = None) -> ToolResult:
        selected_name, _, config = self._load_selected_mpnet(name)
        return ToolResult(
            name="describe_transitions",
            ok=True,
            content=f"Transition list for '{selected_name}'",
            data={"name": selected_name, "transitions": mpnet_utils.describe_transitions(config)},
        )

    def read_notes(self) -> ToolResult:
        notes = self.store.read_notes(self.project, self.task)
        return ToolResult(name="read_notes", ok=True, content="Task notes", data={"notes": notes})

    def save_notes(self, notes: str) -> ToolResult:
        self.store.save_notes(self.project, self.task, notes)
        return ToolResult(name="save_notes", ok=True, content="Saved task notes", data={"notes": notes})

    def create_mpnet(
        self,
        name: str,
        primitive_name: str = "main",
        notes: str | None = None,
        description: str | None = None,
    ) -> ToolResult:
        config = mpnet_utils.create_template_mpnet(primitive_name=primitive_name, notes=notes)
        payload = self._save_selected_mpnet(name, config, description=description)
        return ToolResult(name="create_mpnet", ok=True, content=f"Created MP-Net '{name}'", data=payload)

    def import_mpnet(self, name: str, path: str) -> ToolResult:
        config = mpnet_utils.load_mpnet_config(path)
        payload = self._save_selected_mpnet(name, config, origin_path=str(Path(path).expanduser().resolve()))
        return ToolResult(name="import_mpnet", ok=True, content=f"Imported MP-Net '{name}'", data=payload)

    def edit_mpnet(
        self,
        operation: str,
        arguments: dict[str, Any],
        name: str | None = None,
        description: str | None = None,
    ) -> ToolResult:
        selected_name, _, config = self._load_selected_mpnet(name)
        updated = mpnet_utils.apply_edit(config, operation, arguments)
        payload = self._save_selected_mpnet(selected_name, updated, description=description, set_active=True)
        payload["summary"] = mpnet_utils.summarize_mpnet(updated)
        return ToolResult(
            name="edit_mpnet",
            ok=True,
            content=f"Applied '{operation}' to MP-Net '{selected_name}'",
            data=payload,
        )

    def validate_mpnet(self, name: str | None = None) -> ToolResult:
        selected_name, version, config = self._load_selected_mpnet(name)
        validated = mpnet_utils.validate_mpnet_config(config)
        return ToolResult(
            name="validate_mpnet",
            ok=True,
            content=f"Validated MP-Net '{selected_name}'",
            data={"name": selected_name, "version": version, "summary": mpnet_utils.summarize_mpnet(validated)},
        )

    def list_runs(self) -> ToolResult:
        runs = [asdict(item) for item in self.store.list_runs(self.project, self.task)]
        return ToolResult(name="list_runs", ok=True, content=f"Found {len(runs)} runs", data={"runs": runs})

    def summarize_latest_evals(self) -> ToolResult:
        runs = [
            run for run in self.store.list_runs(self.project, self.task)
            if run.run_type in {"evaluation", "eval", "dataset_eval"}
        ][:5]
        payload = [
            {
                "run_id": run.run_id,
                "status": run.status,
                "policy_id": run.policy_id,
                "dataset_id": run.dataset_id,
                "metrics": run.metrics,
                "summary_path": run.summary_path,
                "started_at": run.started_at,
            }
            for run in runs
        ]
        return ToolResult(
            name="summarize_latest_evals",
            ok=True,
            content=f"Found {len(payload)} evaluation runs",
            data={"evaluations": payload},
        )

    def compare_runs(self, run_a: str, run_b: str) -> ToolResult:
        left = self.store.load_run(self.project, self.task, run_a)
        right = self.store.load_run(self.project, self.task, run_b)
        payload = {
            "run_a": asdict(left),
            "run_b": asdict(right),
            "metric_delta": self._metric_delta(left.metrics, right.metrics),
        }
        return ToolResult(name="compare_runs", ok=True, content=f"Compared runs '{run_a}' and '{run_b}'", data=payload)

    def _metric_delta(self, left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
        delta = {}
        for key in sorted(set(left) | set(right)):
            lhs = left.get(key)
            rhs = right.get(key)
            if isinstance(lhs, (int, float)) and isinstance(rhs, (int, float)):
                delta[key] = rhs - lhs
            else:
                delta[key] = {"left": lhs, "right": rhs}
        return delta

    def pin_artifact(
        self,
        kind: str,
        path: str,
        label: str | None = None,
        metadata: dict[str, Any] | None = None,
        mp_net: str | None = None,
    ) -> ToolResult:
        artifact = ArtifactRef(
            artifact_id=f"{kind}-{utc_now().replace(':', '-').replace('+00:00', 'z')}",
            kind=kind,
            path=str(Path(path).expanduser().resolve()),
            project=self.project,
            task=self.task,
            label=label,
            metadata=metadata or {},
            mp_net=mp_net,
        )
        self.store.save_artifact(self.project, self.task, artifact)
        return ToolResult(name="pin_artifact", ok=True, content=f"Pinned {kind} artifact", data={"artifact": asdict(artifact)})

    def run_demo_mpnet(self) -> ToolResult:
        command = [sys.executable, "-m", "share.scripts.examples.demo_mp_net"]
        record = self.runner.run_subprocess(project=self.project, task=self.task, run_type="demo", command=command)
        return ToolResult(name="run_demo_mpnet", ok=True, content="Executed demo_mp_net example", data={"run": asdict(record)})

    def run_recording(
        self,
        dataset_repo_id: str,
        dataset_root: str,
        single_task: str,
        name: str | None = None,
        num_episodes: int = 1,
        episode_time_s: int = 30,
        interactive: bool = False,
    ) -> ToolResult:
        selected_name, version, config = self._load_selected_mpnet(name)
        run = self.store.create_run(
            self.project,
            self.task,
            run_type="record",
            status="preparing",
            mp_net=selected_name,
            mp_net_version=version,
            dataset_id=dataset_repo_id,
        )
        run_dir = self.store.run_dir(self.project, self.task, run.run_id)
        from share.configs.record import DatasetRecordConfig, RecordConfig

        record_cfg = RecordConfig(
            env=config,
            dataset=DatasetRecordConfig(
                repo_id=dataset_repo_id,
                root=dataset_root,
                single_task=single_task,
                num_episodes=num_episodes,
                episode_time_s=episode_time_s,
            ),
            interactive=interactive,
        )
        config_path = run_dir / "record_config.json"
        import draccus

        with open(config_path, "w", encoding="utf-8") as f, draccus.config_type("json"):
            draccus.dump(record_cfg, f, indent=2)
            f.write("\n")
        command = [sys.executable, "-m", "share.scripts.record", f"--config_path={config_path}"]
        record = self.runner.run_subprocess(
            project=self.project,
            task=self.task,
            run_type="record",
            command=command,
            prepared_run=run,
            mp_net=selected_name,
            mp_net_version=version,
            dataset_id=dataset_repo_id,
            cwd=str(self.repo_root),
        )
        return ToolResult(name="run_recording", ok=True, content="Launched recording workflow", data={"run": asdict(record)})

    def run_training(
        self,
        policy_path: str,
        dataset_repo_id: str,
        dataset_root: str,
        output_dir: str,
        steps: int = 1000,
        batch_size: int = 8,
        eval_freq: int = 0,
        job_name: str | None = None,
    ) -> ToolResult:
        prepared_run = self.store.create_run(
            self.project,
            self.task,
            run_type="training",
            status="preparing",
            policy_id=policy_path,
            dataset_id=dataset_repo_id,
        )
        summary_path = Path(prepared_run.summary_path)
        command = [
            sys.executable,
            "-m",
            "share.scripts.train",
            "--policy-path",
            policy_path,
            "--dataset-repo-id",
            dataset_repo_id,
            "--dataset-root",
            dataset_root,
            "--output-dir",
            output_dir,
            "--steps",
            str(steps),
            "--batch-size",
            str(batch_size),
            "--eval-freq",
            str(eval_freq),
            "--summary-path",
            str(summary_path),
        ]
        if job_name:
            command.extend(["--job-name", job_name])
        record = self.runner.run_subprocess(
            project=self.project,
            task=self.task,
            run_type="training",
            command=command,
            prepared_run=prepared_run,
            policy_id=policy_path,
            dataset_id=dataset_repo_id,
        )
        return ToolResult(name="run_training", ok=True, content="Launched training adapter", data={"run": asdict(record)})

    def run_evaluation(
        self,
        policy_path: str,
        dataset_root: str,
        output_dir: str,
        metrics_file: str | None = None,
    ) -> ToolResult:
        prepared_run = self.store.create_run(
            self.project,
            self.task,
            run_type="evaluation",
            status="preparing",
            policy_id=policy_path,
            dataset_id=dataset_root,
        )
        summary_path = Path(prepared_run.summary_path)
        command = [
            sys.executable,
            "-m",
            "share.scripts.eval_on_dataset",
            "--policy-path",
            policy_path,
            "--dataset-root",
            dataset_root,
            "--output-dir",
            output_dir,
            "--summary-path",
            str(summary_path),
        ]
        if metrics_file:
            command.extend(["--metrics-file", metrics_file])
        record = self.runner.run_subprocess(
            project=self.project,
            task=self.task,
            run_type="evaluation",
            command=command,
            prepared_run=prepared_run,
            policy_id=policy_path,
            dataset_id=dataset_root,
        )
        return ToolResult(name="run_evaluation", ok=True, content="Launched evaluation adapter", data={"run": asdict(record)})

    def register_run(
        self,
        run_type: str,
        status: str,
        notes: str | None = None,
        metrics: dict[str, Any] | None = None,
        command: list[str] | None = None,
    ) -> ToolResult:
        record = self.store.create_run(
            self.project,
            self.task,
            run_type=run_type,
            status=status,
            notes=notes,
            command=command or [],
        )
        record.metrics = metrics or {}
        record.ended_at = utc_now()
        self.store.save_run(self.project, self.task, record)
        return ToolResult(name="register_run", ok=True, content="Registered external run", data={"run": asdict(record)})
